on: [pull_request]

name: Dex Test ChatGPT

jobs:
  chatgpt_comment:
    runs-on: ubuntu-latest
    name: Dex Let chatgpt comment on your PR.
    steps:
      - name: Dex ChatGPT comment
        uses: dex3r/chatgpt-action@HEAD
        id: hello
        with:
          number: ${{ github.event.pull_request.number }}
          openAiApiKey: ${{ secrets.CHATGPT_API_KEY }}
          split: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
